version: '3'

services:
  caetun-server:
    image: caetun
    container_name: caetun-server
    cap_add:
      - NET_ADMIN
      - SYSLOG
    sysctls:
      - net.ipv4.ip_forward=1
    privileged: true
    devices:
      - /dev/net/tun
    environment:
      - MODE=server
    volumes:
      - ./config:/etc/caetun
    networks:
      net:
        ipv4_address: 172.18.0.22

  caetun-client1:
    image: caetun
    container_name: caetun-client1
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - MODE=client
    command: /etc/caetun/client1.conf
    volumes:
      - ./config:/etc/caetun
    networks:
      - net

  caetun-client2:
    image: caetun
    container_name: caetun-client2
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - MODE=client
    command: /etc/caetun/client2.conf
    volumes:
      - ./config:/etc/caetun
    networks:
      - net

networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
